name: Check code format

on:
  workflow_call:

jobs:

  check-code-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '14'
        check-path: 'src'
