name: Check Test Coverage

on:
  workflow_call:

jobs:

  check-test-coverage:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install libsqlite3-dev libgtest-dev lcov -y

    - uses: actions/checkout@v4

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
      with:
        version: 2.0.16

    - name: Create Conan profile
      run: | 
        echo "Conan version ${{ steps.conan.outputs.version }}"
        conan profile detect --force

    - name: Build and Test project
      run: >
        conan create ${{ github.workspace }}
        --profile .github/conan-profiles/linux-gcc-coverage
        --build=missing 
        -s build_type=Release

    - name: Generate coverage
      run: |
        lcov -c -o test-coverage.info -d build 
        lcov -o test-coverage.info -e test-coverage.info "$(pwd)/src/*"

    - name: Generate coverage HTML report
      run: |
        genhtml test-coverage.info -o test-coverage-html

    - name: Archive code coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage-html
        path: test-coverage-html

    - uses: fjlopezs/lcov-reporter-action@v1.0.0
      with:
        lcov-file: test-coverage.info
        fail-drop-percent-threshold: 90
        filter-changed-files: false

