name: Check Test Coverage

on:
  workflow_call:

jobs:

  check-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install libsqlite3-dev libgtest-dev lcov -y

    - uses: actions/checkout@v4

    - name: Build and run tests
      run: |
        export CXXFLAGS="-g -fprofile-arcs -ftest-coverage"
        cmake -B build -S .
        cmake --build build
        ctest --test-dir build

    - name: Generate coverage
      run: |
        lcov -c -o test-coverage.info -d build 
        lcov -o test-coverage.info -e test-coverage.info "$(pwd)/src/*"
        genhtml test-coverage.info -o test-coverage-html

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: test-coverage-html
        path: test-coverage-html

    - uses: fjlopezs/lcov-reporter-action@v1.0.0
      with:
        lcov-file: test-coverage.info
        fail-drop-percent-threshold: 90
        filter-changed-files: false

