name: Run Linters.

on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ZedThree/clang-tidy-review@v0.14.0
      id: review



  
