name: Pull-Request checks

on:
  pull_request:

jobs:

  check-code-quality:
    uses: ./.github/workflows/check-pr-code-quality.yml

  check-code-format:
    uses: ./.github/workflows/check-code-format.yml

  check-test-coverage:
    uses: ./.github/workflows/check-test-coverage.yml

  build-multi-platform:
    uses: ./.github/workflows/build-multi-platform.yml
  



